version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://localhost:27017/PracticeDB
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: